Update Sec7i_FLEXRamp.txt
NAMTeam/Network-Addon-Mod pull request #306
Opened 2021-08-09 16:26 UTC by McDuell

added stability code for MIS MRC adjacent to diagonal D1/E1 ramp branch.

![image](https://user-images.githubusercontent.com/68449011/128739958-42359938-6afa-4a40-afda-ee6e8f11411d.png)

![image](https://user-images.githubusercontent.com/68449011/128739998-61c8beeb-924c-48df-9f88-d44792bf899b.png)

2021-08-10 11:55 UTC, jflann commented
I suspect that Sec7i_FLEXRamp is not the best place for the MRC adjacency code.  Take a look at some of the other files in there with 'ramp' in the name, I think that's where adjacencies should be handled.  @TarkusSC4 could confirm

2021-08-10 14:29 UTC, McDuell commented
The reason I put the code in the Sec7i_FLEXRamp is because there was already existing adjacency code for the A1 that wasn't done by me. Thus I thought that this file would be right place to also contain the D1/E1 adjacencies.

2021-08-10 16:37 UTC, jflann commented
In that case, seems good to me.

2021-08-13 15:50 UTC, jflann requested changes

2021-08-13 15:50 UTC, jflann commented on Controller/RUL2/07_RHW/Sec7i_FLEXRamp/Sec7i_FLEXRamp.txt
> +0x578a9580,1,1,0x57905400,2,1=0x5789a580,1,1,0x57925480,2,1
Transposition error @McDuell 
```
0x578a9500,3,0,0x57905400,2,1=0x578a9500,3,0,0x57925400,2,1
0x578a9500,3,0,0x57905400,0,0=0x578a9500,3,0,0x57925480,0,0
0x578a9580,1,1,0x57905400,0,0=0x578a9580,1,1,0x57925400,0,0
0x578a9580,1,1,0x57905400,2,1=0x578a9580,1,1,0x57925480,2,1
```

2021-08-13 16:17 UTC, jflann approved these changes

2021-08-13 16:17 UTC, jflann approved these changes

2021-08-13 16:29 UTC, merged